name: Auto Merge Development to Main

on:
  workflow_run:
    workflows: ["CI"]
    branches: [development]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge-to-main:
    name: Create PR from Development to Main
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup GitHub CLI
      run: |
        gh --version
        
    - name: Check if PR already exists
      id: check-pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if there's already an open PR from development to main
        pr_count=$(gh pr list --base main --head development --state open --json number | jq length)
        echo "pr_exists=$pr_count" >> $GITHUB_OUTPUT
        
    - name: Create Pull Request
      if: steps.check-pr.outputs.pr_exists == '0'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get the latest commit message from development branch
        git fetch origin development:development
        latest_commit_msg=$(git log -1 --pretty=format:"%s" development)
        
        # Create PR with automatic title and body
        gh pr create \
          --base main \
          --head development \
          --title "Auto-sync: Merge development to main" \
          --body "🤖 **Automated PR**: This PR was automatically created after successful CI on the development branch.

        **Latest Changes:**
        - $latest_commit_msg

        **CI Status:** ✅ All checks passed on development branch

        This PR will merge the latest changes from development into main after review."
          
    - name: Comment on existing PR
      if: steps.check-pr.outputs.pr_exists != '0'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Add a comment to existing PR about new CI success
        pr_number=$(gh pr list --base main --head development --state open --json number | jq -r '.[0].number')
        gh pr comment $pr_number --body "🤖 **CI Update**: New successful CI run on development branch at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"